### ISSUE TITLE
"Edit profile" link broken for some users

### ISSUE THREAD

**Issue by amandafrench** [chnm/thatcamp-org#41]
I have a report from a user jea211 on thatcamp.org that when she logs in, then clicks "Edit Profile" on her People page at http://thatcamp.org/people/jea211, she gets the error message at http://thatcamp.org/wp-admin/profile.php "You do not have sufficient permissions to edit this page." I have reproduced this error on THATCamp Dev with the testing user (login 'testing' pass 'testing') -- log in as 'testing' then see http://thatcampdev.info/people/testing and click "Edit Profile." 

I am not sure what is causing this error, though, since it does not occur for all users. All I can think is that it's something to do with her BuddyPress user capabilities.

**Comment by amandafrench** [comment]
Reoccurring recently -- see user report at http://thatcamp.org/forums/topic/cant-edit-profile-though-im-logged-in/

**Comment by amandafrench** [comment]
Hey @boonebgorges, any idea why this issue is recurring on thatcamp.org? The code in the associated commit that fixed it previously is still there on the site.

**Comment by boonebgorges** [comment]
http://thatcamp.org/forums/topic/cant-edit-profile-though-im-logged-in/#post-5372

I think your diagnosis here sounds correct. When users register at thatcamp.org (instead of a subsite) they are not added as users to any site in the network. As such, there is no site on which they have permission to see the Dashboard.

I've just pushed up a small mu-plugin that ought to solve this. It does the following: when a new user activates her account through BuddyPress (a process that should only occur when registering at thatcamp.org/signup/; subsites are handled through the THATCamp Registrations plugin), the user is added to the main site as a 'subscriber'. This should be enough to let them visit wp-admin/profile.php.

I haven't tested this because I no longer have a good working clone of thatcamp.org, but I think it should do the trick :)

**Comment by amandafrench** [comment]
Dude, @boonebgorges. What's up with the hipster black-framed glasses? Is this to signal to the midwest that you once lived in Brooklyn??

Thanks for the code! Doesn't seem to fix the issue on production (I registered as a new user and tested), but let me investigate a bit more -- if I have to I'll set you up with access to THATCamp production. I think they shut down access to thatcampdev.info; can't remember.

**Comment by boonebgorges** [comment]
More like a signal of my fading youth.

With the code, is the problem that users are not being added as Subscribers on the main site, or is it that being a Subscriber doesn't give people the required permission?

If I can get SSH access, I'll cowboy this one on production for you https://www.bnj.com/blog/cowboy-coding-pink-sombrero/

**Comment by amandafrench** [comment]
That's what I was just looking at -- the test user didn't get added as a Subscriber on the main site; role is Participant. But I got a blank screen at activation, too, although the account did get activated. Lemme see about opening the production gate for you, cowboy.

**Comment by amandafrench** [comment]
I also want to check to see if I've set something somewhere that might be overriding it.

**Comment by boonebgorges** [comment]
The Participant thing is being caused by bbPress. Let me know when 
you've got access for me, and I'll begin my poking.

**Comment by amandafrench** [comment]
check your email

**Comment by boonebgorges** [comment]
Blargh. Typo. It's fixed here and on production, and appears to be working now. Please test.

**Comment by amandafrench** [comment]
Works great! Thanks so much, @boonebgorges -- I always put off asking you this stuff as long as I can, but sometimes there's no other recourse.

**Comment by boonebgorges** [comment]
I'm happy to be your last resort.
